blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/BoettcherDasOriginal/Evolving-Circuitry/discussions
    about: Please ask and answer questions here.
